config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'questions#index'

  resources :questions, only: [:create, :update, :destroy, :new, :edit, :index, :show] do
    resources :answers, only: [:create]
    resources :votes, only: [:create]
    member do
      post :add_topic
      delete :remove_topic
      get :search_topic
    end
  end

  resources :answers, only: [:update, :destroy] do
    resources :comments, only: [:create]
    resources :votes, only: [:create]
  end

  resources :comments, only: [:update, :destroy] do
    resources :comments, only: [:create]
    resources :votes, only: [:create]
  end

  resources :votes, only: [:destroy]

  resources :topics, only: [:create, :show] do
    post :follow
    delete :unfollow
  end
end

app/models/question.rb
class Question < ApplicationRecord
  include Votable

  # Validations
  validates :user_id, presence: true
  validates :question, presence: true, length: { maximum: 250 }

  # Associations
  belongs_to :user
  has_many :answers, dependent: :destroy
  has_and_belongs_to_many :topics

  # Scope
  default_scope { order(created_at: :desc) }
  scope :topic, ->(topic_id) { joins(:topics).where("topics": { id: topic_id }).group(:id) }

  paginates_per 5

  def get_question
    self
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!

  def search_topic
    @question = Question.find(params[:id])
    @results = Topic.search_by_name(params[:q]).where.not(id: @question.topics.pluck(:id))
    respond_to do |format|
      format.js {}
    end
  end

  def add_topic
    @question = Question.find(params[:id])
    topic = Topic.find(params[:topic_id])
    topic.questions << @question
    if topic.save
      flash[:success] = "Topic added successfully"
    else
      flash[:danger] = "Failed to add topic"
    end
    redirect_to @question
  end

  def remove_topic
    @question = Question.find(params[:id])
    topic = Topic.find(params[:topic_id])
    if topic.questions.delete(@question)
      flash[:success] = "Topic removed successfully"
    else
      flash[:danger] = "Failed to remove topic"
    end
    redirect_to @question
  end

  def new
    @question = Question.new
  end

  def edit
    @question = Question.find(params[:id])
  end

  def index
    @questions = Question.all.page(params[:page] || 1)
    @questions = @questions.topic(params[:topic_id]) if params[:topic_id]
  end

  def show
    @question = Question.find(params[:id])
  end

  def create
    @question = Question.new(strong_params)
    @question.user = helpers.current_user

    if @question.save
      flash[:success] = "Question created successfully"
      redirect_to @question
    else
      flash[:warning] = "Failed to create question"
      redirect_back(fallback_location: root_path)
    end
  end

  def update
    @question = Question.find(params[:id])
    @question.attributes = strong_params

    if @question.user != helpers.current_user
      redirect_to @question
    elsif @question.save
      flash[:success] = "Question updated successfully"
      redirect_to @question
    else
      flash[:warning] = "Failed to update question"
      render :edit
    end
  end

  def destroy
    @question = Question.find(params[:id])

    if @question.user == helpers.current_user && @question.destroy!
      flash[:success] = "Question deleted successfully"
      redirect_to questions_path
    else
      flash[:warning] = "Failed to delete question"
      redirect_to @question
    end
  end

  private

  def strong_params
    params.require(:question).permit(:question, :description, :topics)
  end
end

app/views/questions/_current_user_answer.html.haml
- unless question.answers.where(user_id: current_user.id).exists?
  %h3 Answer
  = render "answers/new", question: question, answer: Answer.new
- else
  %h3 Your answer
  = render "answers/answer", answer: question.answers.where(user_id: current_user.id).first

app/views/questions/_item.html.haml
%h4
  = link_to question.question, question, class: "question-link"
%p
  asked by
  = question.user.full_name
%p
  - answer = question.answers.first
  - if answer
    %h5= answer.user.full_name
    %p= answer.answer
= render "votes/vote_buttons", content: question

app/views/questions/_question_content.html.haml
#question-content
  %h3
    = @question.question
  %p
    = simple_format @question.description
  %p
    asked by
    = @question.user.full_name
  = render "votes/vote_buttons", content: @question
  - if @question.user == current_user
    = link_to "Edit question", edit_question_url(@question)

app/views/questions/_topic_search_form.html.haml
%a#show-topic-form.topic-label{"data-target" => "#edit-topics-modal", "data-toggle" => "modal", :type => "button"}
  %span.glyphicon.glyphicon-pencil{"aria-hidden" => "true"}

#edit-topics-modal.modal{"aria-labelledby" => "edit-topics-modal-label", :role => "dialog", :tabindex => "-1"}
  .modal-dialog{:role => "document"}
    .modal-content
      .modal-header
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} &#215;
        %h4#edit-topics-modal-label.modal-title Edit topics
      .modal-body
        %label.sr-only{:for => "topic-search-form"} Search topics
        %input#topic-search-form.form-control{:type => "text"}
        .container-fluid{:style => "position:relative"}
          #topic-search-results.list-group{:style => "display:none;position:absolute;left:0;right:0;max-height:320px;overflow-y:scroll"}
        - question.topics.each do |topic|
          .container-fluid
            = link_to raw("&times;"), remove_topic_question_url(question, topic_id: topic.id), method: :delete, data: { confirm: "Are you sure?" }, class: "remove-topic-link"
            .topic-label= topic.name
      .modal-footer
        %button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} Close
        %button.btn.btn-primary{:type => "button"} Save changes

:javascript
  let url = "#{ search_topic_question_url(question) }";
  let xhr;

  $('#topic-search-form').keyup(function(e) {
    if(xhr) { xhr.abort(); }
    let value = e.target.value;
    if(value) {
      xhr = $.get(url, {'q': value});
    } else {
      $('#topic-search-results').hide();
    }
  });

app/views/questions/_topic_search_result.html.haml
.media
  .media-body
    %h5.media-heading= topic.name
    %p
      = topic.topic_users.count
      Followers
  .media-right
    = image_tag "http://lorempixel.com/32/32/"

app/views/questions/_topics_list.html.haml
- question.topics.each do |topic|
  = link_to topic.name, topic, class: "topic-label"

app/views/questions/edit.html.haml
= form_for @question, html: { class: "form-horizontal" } do |f|
  .form-group
    = f.label :question, class: "col-sm-2 control-label"
    .col-sm-10
      = f.text_field :question, class: "form-control"
  .form-group
    = f.label :description, class: "col-sm-2 control-label"
    .col-sm-10
      = f.text_area :description, class: "form-control"
  .form-group
    .col-sm-offset-2.col-sm-10
      = f.submit class: "btn btn-primary"
      = link_to "Discard changes", question_url(@question), method: :get, class: "btn btn-default"
      = link_to "Delete question", @question, method: :delete, class: "btn btn-danger", data: { confirm: "Are you sure?" }

app/views/questions/index.html.haml
= content_for :style do
  = stylesheet_link_tag 'index_page', 'data-turbolinks-track': 'reload'

.col-md-10
  .feed-item
    - if params[:topic_id].is_a?(String)
      - topic = Topic.find(params[:topic_id])
      .media
        .media-left.media-middle
          %a{:href => "#"}
            = image_tag "http://lorempixel.com/256/256/", width: 96, height: 96
        .media-body.media-middle
          %h4.media-heading= topic.name
      %p= topic.description
      %div
        = render "topics/follow_button", topic: topic
    - else
      %div{style: "font-size: 20px;color: #B92B27;"}= current_user.full_name
      %h4
        %a.ask-question-link{data: {"test-id": "questions-index-ask-question-link", toggle: "modal", target: "#new-question-modal"}}
          Please put you question here?
  - @questions.each do |question|
    .feed-item
      = render "questions/item", question: question
  = paginate @questions
.col-md-2
  %h4 My Feeds
  %hr
  .list-group
    = link_to "Followed Topics", questions_url(topic_id: current_user.topics.pluck(:id)), class: "list-group-item"
    - current_user.topics.each do |topic|
      = link_to topic.name, questions_url(topic_id: topic.id), class: "list-group-item"

app/views/questions/search_topic.js.erb
let results = <%= raw @results.to_json %>
$('#topic-search-results').empty();
<% if @results.empty? %>
  $('#topic-search-results').append(
    '<%= link_to(topics_url(topic: { name: params[:q] }), method: :post, class: "list-group-item") do %>' +
      'Create new topic' +
    '<% end %>'
  );
<% else %>
  <% @results.each do |result| %>
    $('#topic-search-results').append(
      '<%= link_to(add_topic_question_url(@question, topic_id: result.id), method: :post, class: "list-group-item") do %>' +
        '<%= j render "questions/topic_search_result", topic: result %>' +
      '<% end %>'
    );
  <% end %>
<% end %>
$('#topic-search-results').show();

app/views/questions/show.html.haml
%div{data: {"test-id": "question-page"}}
  .col-md-8
    %h4
      %span Topics:

    = render "questions/topics_list", question: @question

    = render "questions/topic_search_form", question: @question

    = render "questions/question_content", question: @question

    #answers
      #current-user-answer
        = render 'questions/current_user_answer', question: @question
      %h3
        = @question.answers.where.not(user_id: current_user.id).count
        Answers
      - @question.answers.where.not(user_id: current_user.id).each do |answer|
        = render "answers/answer", answer: answer

  .col-md-4
    .related-questions
      %h4 Related Questions
      %hr
      - Question.topic(@question.topics.pluck(:id)).limit(20).each do |question|
        .related-question
          = link_to question.question, question