config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'questions#index'

  resources :questions, only: [:create, :update, :destroy, :new, :edit, :index, :show] do
    resources :answers, only: [:create]
    resources :votes, only: [:create]
    member do
      post :add_topic
      delete :remove_topic
      get :search_topic
    end
  end

  resources :answers, only: [:update, :destroy] do
    resources :comments, only: [:create]
    resources :votes, only: [:create]
  end

  resources :comments, only: [:update, :destroy] do
    resources :comments, only: [:create]
    resources :votes, only: [:create]
  end

  resources :votes, only: [:destroy]

  resources :topics, only: [:create, :show] do
    post :follow
    delete :unfollow
  end
end

app/models/topic.rb
class Topic < ApplicationRecord
  # Validations
  validates :name, presence: true

  # Associations
  has_and_belongs_to_many :users
  has_and_belongs_to_many :questions

  # PG Search
  include PgSearch
  pg_search_scope :search_by_name, against: :name, :using => {
    :tsearch => {:prefix => true}
  }
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def create
    @topic = Topic.new(topic_params)

    if @topic.save
      flash[:success] = "Topic created successfully"
      redirect_to @topic
    else
      flash[:danger] = "Failed to follow topic"
      redirect_to "/"
    end
  end

  def show
    @topic = Topic.find(params[:id])
  end

  def follow
    @topic = Topic.find(params[:topic_id])
    user = helpers.current_user
    follow = TopicUser.new(topic_id: @topic.id, user_id: user.id)
    if follow.save
      flash[:success] = "Topic followed successfully"
    else
      flash[:danger] = "Failed to follow topic"
    end
    redirect_to @topic
  end

  def unfollow
    @topic = Topic.find(params[:topic_id])
    user = helpers.current_user
    follows = TopicUser.where(topic_id: @topic.id, user_id: user.id)
    unless follows.empty?
      follows.delete_all
      flash[:success] = "Topic unfollowed successfully"
    else
      flash[:danger] = "Failed to unfollow topic"
    end
    redirect_to @topic
  end

  private

  def topic_params
    params.require(:topic).permit(:name, :description)
  end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_follow_button.html.haml
- if TopicUser.where(topic_id: topic.id, user_id: current_user.id).exists?
  = link_to "Unfollow Topic | #{topic.users.count}", topic_unfollow_url(topic), method: :delete, class: "btn btn-gray text-right"
- else
  = link_to "Follow Topic | #{topic.users.count}", topic_follow_url(topic), method: :post, class: "btn btn-blue text-right"

app/views/topics/show.html.haml
.row.topic-header
  = image_tag "http://lorempixel.com/256/256/"
  %h3= @topic.name
  %span
    = render "topics/follow_button", topic: @topic
%hr
.row
  .col-md-8
    %h4 Feed
    %hr
    - @topic.questions.each do |question|
      = render "questions/item", question: question
      %hr
  .col-md-4
    About